### ISSUE TITLE
How to intergrate GTK with penrose

### ISSUE THREAD

**Issue by krolmiki2011** [sminez/penrose-from-scratch#1]
Hello i creating my window manager and i dont know how to integrate GTK Decorations with Penrose. Please help.

**Comment by sminez** [comment]
I'll need a little more information on what it is you are trying to achieve to be able to help I'm afraid. For one thing, GTK decorations are all client side so there isn't any involvement from the window manager. As for Penrose providing decorations itself, that _is_ possible in theory but it's not something I've looked at previously.

Also this is a repo showing one particular set up for a window manager using Penrose. If you are wanting to implement custom extensions and behaviours then you almost certainly want to be looking at the main Penrose repo itself 🙂
